version: '3.8'

services:
  purpleschoolhw:
    image: ghcr.io/mixaboo/purpleschoolhw/purpleschoolhw:develop
    container_name: purpleschoolhw
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env



  mongo:
      image: mongo
      container_name: mongo
      restart: always
      env_file:
        - .env
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      ports:
        - 27017:27017
      volumes:
        - ./mongo-data:/data/db
      command: --wiredTigerCacheSizeGB 1.5
